spring:            #全局配置
  thymeleaf:
    cache: false
  profiles:
    active: dev
  servlet:
    multipart:
      location: /Users/elvislin/Documents/temp
      max-file-size: 1024MB
      max-request-size: 1024MB

minio:
  endpoint: http://127.0.0.1:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: twitter

comment.avatar: /images/avatar.jpg
